ZSH="$HOME/.oh-my-zsh"
ZSHRC="$HOME/.zsh"
JAVA_HOME="/usr/lib/jvm/jdk-14.0.2"
PATH=$JAVA_HOME/bin:$PATH
PATH=$HOME/Scripts:$PATH
PSQL_PAGER=pspg
EDITOR="/usr/bin/nvim"
TERMINAL="/usr/bin/xfce4-terminal"
WINDOWS="/run/media/dribe/Windows 10/Users/User/"
