#!/bin/sh

COLORS=(black red green yellow blue magenta cyan white)
HEX_DARK=("#413f54" "#c97074" "#63ae8d" "#e5ac91" "#6c90c0" "#de8bc1" "#8cd0d1" "#dddbdc")
HEX_BRIGHT=("#709081" "#dda3a1" "#7bd1a2" "#eee0af" "#95bcff" "#e099d3" "#94dfe2" "#fffeff")

# ansi codes
reset="\e[;39m"
normal="\e[0;"
inverse="\e[7;"

for i in $(seq 0 1 8); do
    COLOR=${COLORS[$i]}
    DARK="$inverse$((i+30))m${HEX_DARK[$i]}$reset"
    BRIGHT="$inverse$((i+90))m${HEX_BRIGHT[$i]}$reset"
    echo -e "$COLOR\t$DARK\t$BRIGHT"
done
