#!/bin/zsh

BASEDIR=$HOME/.config/polybar

case $1 in
    (completions|comp)  $EDITOR $HOME/.oh-my-zsh/completions/_pb;;
    (colors|col)        $EDITOR $BASEDIR/colors.ini;;
    (config|conf)       $EDITOR $BASEDIR/config.ini;;
    (fonts|font)        $EDITOR $BASEDIR/fonts.ini;;
    
    (modules|module|mod|m|-m) case $2 in
        (battery)                   $EDITOR $BASEDIR/modules/battery.ini;;
        (bluetooth)                 $EDITOR $BASEDIR/modules/bluetooth.ini;;
        (cpu)                       $EDITOR $BASEDIR/modules/cpu.ini;;
        (date|time)                 $EDITOR $BASEDIR/modules/date.ini;;
        (fs-root)                   $EDITOR $BASEDIR/modules/fs-root.ini;;
        (fs-home)                   $EDITOR $BASEDIR/modules/fs-home.ini;;
        (memory|ram)                $EDITOR $BASEDIR/modules/memory.ini;;
        (mic-volume|mic)            $EDITOR $BASEDIR/modules/mic-volume.ini;;
        (network|wifi)              $EDITOR $BASEDIR/modules/network.ini;;
        (poweroff|shutdown)         $EDITOR $BASEDIR/modules/poweroff.ini;;
        (pulseaudio|audio|volume)   $EDITOR $BASEDIR/modules/pulseaudio.ini;;
        (restart)                   $EDITOR $BASEDIR/modules/restart.ini;;
        (xkeyboard|keyboard|layout) $EDITOR $BASEDIR/modules/xkeyboard.ini;;
        (xwindow|window)            $EDITOR $BASEDIR/modules/xwindow.ini;;
        (xworkspaces|workspaces)    $EDITOR $BASEDIR/modules/xworkspaces.ini;;
        ('') print -P "You must specify the module name" >&2;;
        (*) print -P "Invalid module name: %F{9}$2%F{-1}" >&2;;
    esac;;
    
    (dock|apps|d|-d) case $2 in
        (discord)  $EDITOR $BASEDIR/modules/dock/discord-dock.ini;;
        (firefox)  $EDITOR $BASEDIR/modules/dock/firefox-dock.ini;;
        (intellij) $EDITOR $BASEDIR/modules/dock/intellij-dock.ini;;
        (nicotine) $EDITOR $BASEDIR/modules/dock/nicotine-dock.ini;;
        (spotify)  $EDITOR $BASEDIR/modules/dock/spotify-dock.ini;;
        (telegram) $EDITOR $BASEDIR/modules/dock/telegram-dock.ini;;
        (whatsapp) $EDITOR $BASEDIR/modules/dock/whatsapp-dock.ini;;
        (code)     $EDITOR $BASEDIR/modules/dock/code-dock.ini;;
        ('') print -P "You must specify the dock application" >&2;;
        (*) print -P "Invalid dock application: %F{9}$2%F{-1}" >&2;;
    esac;;
    
    (spotify|s|-s) case $2 in
        (next)                  $EDITOR $BASEDIR/modules/spotify/next.ini;;
        (playpause|play)        $EDITOR $BASEDIR/modules/spotify/playpause.ini;;
        (previous|prev)         $EDITOR $BASEDIR/modules/spotify/previous.ini;;
        (spotify|playback|'')   $EDITOR $BASEDIR/modules/spotify/spotify.ini;;
        (*) print -P "Invalid spotify module: %F{9}$2%F{-1}" >&2;;
    esac;;
    
    (bar|b|-b) case $2 in
        (top)        $EDITOR $BASEDIR/bars/top.ini;;
        (bottom)     $EDITOR $BASEDIR/bars/bottom.ini;;
        (main)       $EDITOR $BASEDIR/bars/main.ini;;
        ('') print -P "You must specify the bar name" >&2;;
        (*) print -P "Invalid bar name: %F{9}$2%F{-1}" >&2;;
    esac;;

    ('') print -P "You must specify the config argument" >&2;;
    (*) print -P "Invalid argument: %F{9}$1%F{-1}" >&2;;
esac
