#!/bin/sh

if [ $# -eq 0 ]; then
    killall polybar || polybar main & >/dev/null
else case $1 in
        --on)   polybar main & >/dev/null;;
        --off)  killall polybar;;
        *)      echo -e "\e[1;31mInvalid option!\e[0;39m"
esac fi
