#!/bin/sh

cd ~/Repos/dot-files

BASEDIR=usr/share # system configs
rsync -a /$BASEDIR/fonts                     $BASEDIR/

BASEDIR=home/dribe # global configs
rsync -a /$BASEDIR/Scripts                   $BASEDIR/
rsync -a /$BASEDIR/.vimrc                    $BASEDIR/
rsync -a /$BASEDIR/.Xresources               $BASEDIR/
rsync -a /$BASEDIR/.zshrc                    $BASEDIR/
rsync -a /$BASEDIR/.zshenv                   $BASEDIR/
rsync -a /$BASEDIR/.zsh/aliases.zsh          $BASEDIR/.zsh/
rsync -a /$BASEDIR/.zsh/cli-commands.sh      $BASEDIR/.zsh/
rsync -a /$BASEDIR/.zsh/functions.zsh        $BASEDIR/.zsh/
rsync -a /$BASEDIR/.oh-my-zsh/completions    $BASEDIR/.oh-my-zsh/

BASEDIR=home/dribe/.config # personal configs
rsync -a /$BASEDIR/awesome                   $BASEDIR/
rsync -a /$BASEDIR/firefox                   $BASEDIR/
rsync -a /$BASEDIR/gtk-3.0                   $BASEDIR/
rsync -a /$BASEDIR/lvim                      $BASEDIR/
rsync -a /$BASEDIR/neofetch/config.conf      $BASEDIR/neofetch/
rsync -a /$BASEDIR/nvim                      $BASEDIR/
rsync -a /$BASEDIR/polybar                   $BASEDIR/
rsync -a /$BASEDIR/ranger                    $BASEDIR/
rsync -a /$BASEDIR/rofi                      $BASEDIR/
rsync -a /$BASEDIR/spicetify/config-xpui.ini $BASEDIR/spicetify/
rsync -a /$BASEDIR/vimium                    $BASEDIR/
rsync -a /$BASEDIR/xfce4/terminal            $BASEDIR/xfce4/

# ansi codes
col0="\e[0;39m"     # normal
col1="\e[32m"       # green
col2="\e[1;32m"     # bold green
col3="\e[1;31m"     # bold red

########## git prompt menu ##########

# add all changes locally
git add .

# catch -m option and avoid git prompt menu
if  [[ $1 = "-m" ]]; then
    shift
    git status &&
    git commit -am "${@}" &&
    git push &&
    exit 0 || exit 1
fi

opt=0
while [[ $opt != [nN6] && $opt != 'push' ]]; do
    echo -e "${col1}1${col0}) ${col2}log ${col0}commit history"
    echo -e "${col1}2${col0}) ${col0}show ${col2}diff${col0}erences"
    echo -e "${col1}3${col0}) ${col2}show ${col0}last commit"
    echo -e "${col1}4${col0}) ${col0}show git ${col2}status${col0}"
    echo -e "${col1}5${col0}) ${col2}commit ${col0}latest changes"
    echo -e "${col1}6${col0}) ${col2}push ${col0}latest commits"
    echo -ne "${col2}n${col0}/${col2}N ${col0}to cancel: ${col2}"
    read opt && echo -e "${col0}";
    case $opt in
        1|log) git log;;
        2|diff) git diff HEAD;;
        3|show) git show;;
        4|status) git status;;
        5|commit) echo -ne "Enter commit message: ${col2}" &&
            read msg && 
            echo -ne "${col0}" &&
            git commit -am "${msg}" && 
            echo '';;
        6|push) git push;;
        n|N) continue;;
        *) echo -e "${col3}Invalid option!${col0}";
    esac
done

