#!/bin/sh

case $1 in
    # --entire-screen
        # --save --path='~/Pictures/screenshots'
        -es) scrot "/home/dribe/Pictures/screenshots/%y-%m-%d-%H:%M:%S.png";;
        # --save --path='$1'
        -esp) scrot "$2/%y-%m-%d-%H:%M:%S.png";;
        # --copy-to-clipboard
        -ec) scrot "/home/dribe/Pictures/screenshots/temp.png" &&
            xclip -se c -t image/png -i /home/dribe/Pictures/screenshots/temp.png &&
            rm /home/dribe/Pictures/screenshots/temp.png;;
        # --copy-to-clipboard --delay
        -ecd) scrot -d $2 "/home/dribe/Pictures/screenshots/temp.png" &&
            xclip -se c -t image/png -i /home/dribe/Pictures/screenshots/temp.png &&
            rm /home/dribe/Pictures/screenshots/temp.png;;
    # --region
        # --save --path='~/Pictures/screenshots'
        -rs) scrot "/home/dribe/Pictures/screenshots/%y-%m-%d-%H:%M:%S.png" \
            -a $(slop -qf "%x,%y,%w,%h");;
        # --save --path='$1'
        -rsp) scrot "$2/%y-%m-%d-%H:%M:%S.png" -a $(slop -qf "%x,%y,%w,%h");;
        # --copy-to-clipboard
        -rc|*) scrot "/home/dribe/Pictures/screenshots/temp.png" \
            -a $(slop -qf "%x,%y,%w,%h") && 
            xclip -se c -t image/png -i /home/dribe/Pictures/screenshots/temp.png &&
            rm /home/dribe/Pictures/screenshots/temp.png;;
esac
