#!/bin/sh

# ansi codes
black="\e[30m"
red="\e[31m"
green="\e[32m"
yellow="\e[33m"
blue="\e[34m"
magenta="\e[35m"
cyan="\e[36m"
white="\e[37m"
normal="\e[0;39m"

cd $HOME/Repos/dot-files

# configs
cp $HOME/.config/awesome/rc.lua         awesome/rc.lua
cp $HOME/.config/neofetch/config.conf   neofetch/config.conf
cp $HOME/.config/polybar/config.ini     polybar/config.ini
cp $HOME/.config/nvim/init.vim          vim/init.vim
cp $HOME/.vimrc                         vim/.vimrc

# zshrc
cp $HOME/.zshrc                         zshrc/.zshrc
cp $HOME/.zshenv                        zshrc/.zshenv
cp $HOME/.zsh/aliases.zsh               zshrc/aliases.zsh
cp $HOME/.zsh/cli-commands.sh           zshrc/cli-commands.sh
cp $HOME/.zsh/functions.zsh             zshrc/functions.zsh

# scripts
cp -r $HOME/Scripts/* Scripts

# add all changes locally
git add .

# catch -m option and avoid git prompt menu
if  [[ $1 = "-m" ]]; then
    shift
    git status &&
    git commit -am "${@}" &&
    git push &&
    exit 0 || exit 1
fi

# git prompt menu
opt=0
while [[ $opt != [nN5] ]]; do
    echo -e "${green}1) ${normal}git log"
    echo -e "${green}2) ${normal}git show"
    echo -e "${green}3) ${normal}git status"
    echo -e "${green}4) ${normal}git commit"
    echo -e "${green}5) ${normal}git push"
    echo -ne "${red}n/N ${normal}to cancel: "
    read opt
    echo '';
    case $opt in
        1) git log;;
        2) git show;;
        3) git status;;
        4) echo -n "Enter commit message: " &&
            read msg && 
            git commit -am "${msg}" && 
            echo '';;
        5) git push;;
        *) echo -e "${red}Invalid option!${normal}";
    esac
done

