#!/bin/sh

# copy function
copy() {
    [ -d $1 ] && cp -r $1 $2
    [ -f $1 ] && cp $1 $2
}

cd $HOME/Repos/dot-files
copy ~/Scripts                              .
copy ~/.zshrc                               zshrc
copy ~/.zshenv                              zshrc
copy ~/.zsh/aliases.zsh                     zshrc
copy ~/.zsh/cli-commands.sh                 zshrc
copy ~/.zsh/functions.zsh                   zshrc
copy ~/.Xresources                          xresources
copy ~/.vimrc                               vim
copy ~/.config/nvim                         .
copy ~/.config/rofi                         .
copy ~/.config/polybar                      .
copy ~/.config/awesome                      .
copy ~/.config/gtk-3.0/settings.ini         gtk
copy ~/.config/spicetify/config-xpui.ini    spicetify
copy ~/.config/neofetch/config.conf         neofetch
copy /usr/share/fonts                       .

# ansi codes
col0="\e[0;39m"     # normal
col1="\e[32m"       # green
col2="\e[1;32m"     # bold green
col3="\e[1;31m"     # bold red

########## git prompt menu ##########

# add all changes locally
git add .

# catch -m option and avoid git prompt menu
if  [[ $1 = "-m" ]]; then
    shift
    git status &&
    git commit -am "${@}" &&
    git push &&
    exit 0 || exit 1
fi

opt=0
while [[ $opt != [nN6] && $opt != 'push' ]]; do
    echo -e "${col1}1${col0}) ${col2}log ${col0}commit history"
    echo -e "${col1}2${col0}) ${col0}show ${col2}diff${col0}erences"
    echo -e "${col1}3${col0}) ${col2}show ${col0}last commit"
    echo -e "${col1}4${col0}) ${col0}show git ${col2}status${col0}"
    echo -e "${col1}5${col0}) ${col2}commit ${col0}latest changes"
    echo -e "${col1}6${col0}) ${col2}push ${col0}latest commits"
    echo -ne "${col2}n${col0}/${col2}N ${col0}to cancel: ${col2}"
    read opt && echo -e "${col0}";
    case $opt in
        1|log) git log;;
        2|diff) git diff HEAD;;
        3|show) git show;;
        4|status) git status;;
        5|commit) echo -ne "Enter commit message: ${col2}" &&
            read msg && 
            echo -ne "${col0}" &&
            git commit -am "${msg}" && 
            echo '';;
        6|push) git push;;
        n|N) continue;;
        *) echo -e "${col3}Invalid option!${col0}";
    esac
done

